### ISSUE TITLE
Unable to submit lesson with `learn submit`

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/angular-hello-world-lab#11]
I'm running `learn submit` and getting the following error message:

```
[13:02:27] (master) angular-hello-world-lab-Continued-Education
// ♥ learn submit
Adding changes...
Committing changes...
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
Submitting lesson...
Hmm...this doesn't appear to be a Learn lesson. Are you in the right directory?
```

In the meantime, I've submitted a manual pull request.

**Comment by AnnJohn** [comment]
hi @ivalentine is this still an issue? if so, could you actually file a bug report since it looks like a product/engineering issue? thanks.

**Comment by ghost** [comment]
Hi, having the same problem has someone looked at the above 
this what I am having
 [13:35:34] (master) simple-nesting-london-web-100818
// ♥ learn submit
Adding changes...
Committing changes...
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
Submitting lesson...
Hmm...this doesn't appear to be a Learn lesson. Are you in the right directory?
