### ISSUE TITLE
Lab does not include app/app.js

### ISSUE THREAD

**Issue by kronosapiens** [learn-co-curriculum/angular-hello-world-lab#13]
This lab doesn't mention that the student needs to create an app/app.js file to initialize the module. This information is covered in other labs, but not here.

Further, it seems as though this lab duplicates the material found in some other labs.

**Comment by AnnJohn** [comment]
thanks @kronosapiens. Could you let us know too which earlier labs specifically that have the duplicate material?

**Comment by kronosapiens** [comment]
Angular Modules I believe.

**Comment by ipc103** [comment]
Thanks @kronosapiens - I updated the instructions to include directions about creating the `app.js` file.

As for the duplicate material - will raise that in a separate issue. Thanks again!
