### ISSUE TITLE
Learn command not working to run tests

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/angular-hello-world-lab#3]
The steps to install karma are not listed on this lab, and we are not taught how to install them until the testing controllers lab. Maybe add the instructions:

 $ sudo npm install -g karma-cli
$ npm install karma --save-dev
$ npm install jasmine-core --save-dev
$ npm install karma-spec-reporter --save-dev
$ npm install karma-jasmine --save-dev
$ npm install karma-chrome-launcher --save-dev

so that students know how to get the test suite to function.

**Comment by AnnJohn** [comment]
hi @Lukeghenco we'll update the instructions on this lab, but you'll need to update the learn gem before getting started on these angular labs.  Run 'gem update learn-test' and that should work for all labs going forward. 

Thanks!

**Comment by Lukeghenco** [comment]
Hi, AnnJohn. My learn gem was already current. Joe Burgess had me do that last weekend.

**Comment by Lukeghenco** [comment]
You've been invited to join HelloFax by lukeghenco@gmail.com. HelloFax lets you send and receive faxes from the browser. Join now and we'll both get 5 free fax pages.

Accept invitation: https://www.hellofax.com/?ref=5b5e78ad&amp%3Bs=F&utm_campaign=friend_invite&utm_source=default&utm_medium=email&utm_content=original

Thanks for going paperless!

The HelloFax Team
