### ISSUE TITLE
Karma doesn't work in Nitrous IDE with Chrome

### ISSUE THREAD

**Issue by MitulMistry** [learn-co-curriculum/angular-hello-world-lab#4]
Running the tests, I'd keep getting: `ERROR [launcher]: Cannot start Chrome`

The only way I could get it to work was to reconfigure Karma to use PhantomJS. So under karma.conf.js for plugins, I have `require("karma-phantomjs-launcher"),` and `browsers: ['PhantomJS'],`

I had run `npm install karma --save-dev` before I edited the file, so I had to then run `npm install karma-phantomjs-launcher --save-dev` to install the launcher. I already had PhantomJS installed on the Nitrous container, but if not you have to run `sudo apt-get install phantomjs`

All labs in this unit using Karma will probably need to be reconfigured to use PhantomJS for anyone using Nitrous. Obviously students working locally would probably prefer using Chrome or Firefox, so  you may need separately configured labs available or some other solution.

Hope this helps.

**Comment by AnnJohn** [comment]
hi @MitulMistry, running these labs if you're using Nitrous won't work and so what we've been doing is sending students flash drives loaded with Linux. You should have received one, so I'm going to close this issue. 

But fi you haven't, please email me at ann@flatironschool.com and we'll make sure you get one. 

Thanks!
